### ISSUE TITLE
Fix isBaseDataVariableType (ModelToJson.cpp)

### ISSUE THREAD

**Issue by wlkrm** [umati/Dashboard-OPCUA-Client#15]
Some BaseDataVariableTypes (e.g. " "->"i=15318" are not identified as BaseDataVariableType. Currently we add them manually. We should find the root cause and fix it.

**Comment by mdornaus** [comment]
I think the problem is not that the Property ofBaseDataVariableType is red in false somewhere, but that the Nodes get a wrong NodeType with an empty Uri because the VariableTypes are red in with the correct Uri and this is set for the TypeNodes. But somehow duplicates exists that don't have an Uri and this have ofBaseDataVariableType set wrong.

So basically we can do 2 things here, either set the ofBaseDataVariableType for the duplicates correct or exchange the duplicates by the full specified Typenodes with Uri.

I assume that there is a reason why some Typedefinitions don't include an Uri?

**Comment by Kantiran91** [comment]
@ccvca : We think the root cause are this lines:
https://github.com/umati/Dashboard-OPCUA-Client/blob/d6e92f21138ba353fd859689533cf676baf2ee44/OpcUaClient/Converter/UaToModelConverter.cpp#L25-L27

Do you have any idea, why this code was added?

If we remove this lines the isBaseDataVariableType is set correct. Do you think the remove could have some side effects?

**Comment by ccvca** [comment]
> @ccvca : We think the root cause are this lines:
> 
> https://github.com/umati/Dashboard-OPCUA-Client/blob/d6e92f21138ba353fd859689533cf676baf2ee44/OpcUaClient/Converter/UaToModelConverter.cpp#L25-L27
> 
> Do you have any idea, why this code was added?
> 
> If we remove this lines the isBaseDataVariableType is set correct. Do you think the remove could have some side effects?

This code is according to the NodeSet2 XML-Files and string definition of NodeIds, where one namespace is defined as a default. E.g. i=12 is identical to ns=0;i=12

Where does this cause problems? When `getUriFromNsIndex` is used in all places, there should no be a problem.

**Comment by Kantiran91** [comment]
@mdornaus This will be fix  with https://github.com/umati/Dashboard-OPCUA-Client/pull/431, correct?

**Comment by GoetzGoerisch** [comment]
Solved with #431
